# Generated by Django 3.1.13 on 2022-07-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_Air',
            fields=[
                ('quote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quote.quote')),
                ('cargo_weight', models.FloatField()),
                ('cargo_dimension_length', models.CharField(max_length=100)),
                ('cargo_dimension_width', models.CharField(max_length=100)),
                ('cargo_dimension_height', models.CharField(max_length=100)),
            ],
            bases=('quote.quote',),
        ),
    ]
