# Generated by Django 3.2.4 on 2022-11-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20221115_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='incoterm',
            field=models.CharField(choices=[('EX', 'EX Works'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('DAP', 'DAP'), ('OTHER', 'Other')], default='EX', max_length=30),
        ),
    ]
