# Generated by Django 3.2.4 on 2023-02-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20221224_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='county_destination',
            new_name='Country_of_Destination',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='county_origin',
            new_name='Country_of_Origin',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='goods_category',
        ),
        migrations.AddField(
            model_name='quote',
            name='Nature_of_Cargo',
            field=models.CharField(choices=[('Dangerous', 'Dangerous'), ('Non-Dangerous', 'Non-Dangerous')], default='No', max_length=30),
        ),
    ]
