# Generated by Django 3.2.4 on 2023-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20230220_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote_air',
            old_name='cargo_dimension_height',
            new_name='Volume_CBM',
        ),
        migrations.RemoveField(
            model_name='quote_air',
            name='cargo_dimension_length',
        ),
        migrations.RemoveField(
            model_name='quote_air',
            name='cargo_dimension_width',
        ),
        migrations.AlterField(
            model_name='quote',
            name='Nature_of_Cargo',
            field=models.CharField(choices=[('', '------'), ('Dangerous', 'Dangerous'), ('Non-Dangerous', 'Non-Dangerous')], default='No', max_length=30),
        ),
    ]
