# Generated by Django 3.2.4 on 2023-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20230220_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_sea',
            name='container_size',
            field=models.CharField(choices=[('', '-------'), ('1x20FT', '1x20FT'), ('1x40FT', '1x40FT'), ('1x40HC', '1x40HC'), ('1x40 Reefer', '1x40 Reefer')], default='No', max_length=100),
        ),
    ]
