# Generated by Django 3.2.4 on 2023-02-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_alter_quote_sea_container_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote_road',
            old_name='truck_type',
            new_name='Truck_Size',
        ),
        migrations.RenameField(
            model_name='quote_road',
            old_name='cargo_dimension_height',
            new_name='Volume_CBM',
        ),
        migrations.RemoveField(
            model_name='quote_road',
            name='cargo_dimension_length',
        ),
        migrations.RemoveField(
            model_name='quote_road',
            name='cargo_dimension_width',
        ),
        migrations.AddField(
            model_name='quote_road',
            name='Additional_Information',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
