# Generated by Django 3.2.4 on 2023-02-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_auto_20230221_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote_warehouse',
            old_name='special_delivery',
            new_name='Additional_Information',
        ),
        migrations.AddField(
            model_name='quote_warehouse',
            name='Nature_of_Cargo',
            field=models.CharField(blank=True, choices=[('', '-------------------'), ('Non-Dangerous', 'Non-Dangerous'), ('Dangerous', 'Dangerous')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quote_warehouse',
            name='Volume_CBM',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
