# Generated by Django 3.1.13 on 2022-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_quote_quote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_type',
            field=models.CharField(max_length=20),
        ),
    ]
