# Generated by Django 3.1.13 on 2022-07-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0012_auto_20220726_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_owner',
        ),
        migrations.AddField(
            model_name='quote_air',
            name='quote_owner',
            field=models.CharField(default='000', max_length=30),
        ),
    ]
