# Generated by Django 3.1.13 on 2022-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0023_auto_20220730_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_app',
            name='quote_serial_no',
            field=models.CharField(default='000', max_length=30),
        ),
    ]
