# Generated by Django 3.1.13 on 2022-08-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0027_quote_app_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='quotation',
            field=models.CharField(max_length=30),
        ),
    ]
