# Generated by Django 3.1.13 on 2022-08-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0028_auto_20220823_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
