# Generated by Django 3.1.13 on 2022-08-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0030_auto_20220823_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='buying_port_charges_dest',
            new_name='buying_airport_charges',
        ),
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='margin_port_charges_dest',
            new_name='margin_airport_charges',
        ),
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='selling_port_charges_dest',
            new_name='selling_airport_charges',
        ),
    ]
