# Generated by Django 3.1.13 on 2022-08-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0031_auto_20220824_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='buying_other_charges',
            new_name='buying_other_charges_A',
        ),
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='buying_port_charges',
            new_name='margin_other_charges_A',
        ),
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='margin_other_charges',
            new_name='selling_other_charges_A',
        ),
        migrations.RemoveField(
            model_name='staff_pricing_quotation',
            name='margin_port_charges',
        ),
        migrations.RemoveField(
            model_name='staff_pricing_quotation',
            name='selling_other_charges',
        ),
        migrations.RemoveField(
            model_name='staff_pricing_quotation',
            name='selling_port_charges',
        ),
    ]
