# Generated by Django 3.1.13 on 2022-08-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0033_auto_20220824_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('percentage', models.CharField(max_length=100)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff_pricing_quotation',
            name='buying_terminal_handling',
        ),
        migrations.RemoveField(
            model_name='staff_pricing_quotation',
            name='margin_terminal_handling',
        ),
        migrations.RemoveField(
            model_name='staff_pricing_quotation',
            name='selling_terminal_handling',
        ),
    ]
