# Generated by Django 3.1.13 on 2022-08-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0035_auto_20220825_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='customs_value',
            new_name='customs_value_bp',
        ),
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='fob_value',
            new_name='customs_value_margin',
        ),
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='freight_charges',
            new_name='customs_value_sp',
        ),
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='hs_code',
            new_name='fob_value_bp',
        ),
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='insurance',
            new_name='fob_value_margin',
        ),
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='sub_total_duties',
            new_name='fob_value_sp',
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='freight_charges_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='freight_charges_margin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='freight_charges_sp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='hs_code_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='hs_code_margin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='hs_code_sp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='insurance_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='insurance_margin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='insurance_sp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='sub_total_duties_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='sub_total_duties_margin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='sub_total_duties_sp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quote_app',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quote_warehouse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quotetype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
