# Generated by Django 3.1.13 on 2022-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0036_auto_20220831_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_pricing_quotation',
            name='sub_total_taxes',
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='buying_total_destination',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='buying_total_origin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='grand_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='margin_total_destination',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='margin_total_origin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='selling_total_destination',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='selling_total_origin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='sub_total_duties_bp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='sub_total_duties_margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='sub_total_duties_sp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='total_tax',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='percentage',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
