# Generated by Django 3.1.13 on 2022-09-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0038_auto_20220905_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_pricing_quotation',
            old_name='grand_total',
            new_name='grand_total_bp',
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='grand_total_margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_pricing_quotation',
            name='grand_total_sp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
