# Generated by Django 3.1.13 on 2022-09-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0039_auto_20220907_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
