# Generated by Django 3.1.13 on 2022-09-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0040_taxes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='percentage',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=100),
        ),
    ]
