# Generated by Django 3.1.13 on 2022-09-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0042_auto_20220929_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
