# Generated by Django 3.1.13 on 2022-10-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0044_auto_20221004_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='excise_duty',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='idf_fee',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='import_duty',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='levies',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='railway_levy',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='total_tax',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='vat',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
