# Generated by Django 3.1.13 on 2022-10-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0046_auto_20221016_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_pricing_quotation',
            name='total_tax',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
