# Generated by Django 3.1.13 on 2022-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('air', 'Air Freight'), ('sea', 'Sea Freight'), ('road', 'Road Freight'), ('warehouse', 'Ware Housing')], default='sea', max_length=20)),
                ('cargoload', models.CharField(choices=[('full', 'Full Container(FCL)'), ('less', 'Less Than Container Load(LCL)'), ('conventional', 'Conventional Cargo/Bulk')], default='full', max_length=20)),
                ('incoterms', models.CharField(choices=[('EX', 'EX Works'), ('FOB', 'FOB'), ('CRF', 'CRF'), ('DAP', 'DAP'), ('OTHER', 'Other')], default='EX', max_length=20)),
                ('container_size', models.CharField(max_length=20)),
                ('cargo_length', models.CharField(max_length=20)),
                ('cargo_width', models.CharField(max_length=20)),
                ('cargo_height', models.CharField(max_length=20)),
                ('country_origin', models.CharField(max_length=100)),
                ('collection_address', models.CharField(max_length=500)),
                ('cargo_description', models.CharField(max_length=500)),
                ('goods_category', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20)),
                ('special_instructions', models.CharField(max_length=1000)),
            ],
        ),
    ]
