# Generated by Django 3.1.13 on 2022-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='goods_category',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
    ]
