# Generated by Django 3.1.13 on 2022-04-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_auto_20220415_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='owner',
            field=models.CharField(default='anonymous', max_length=1000),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quote_number',
            field=models.CharField(default='00000', max_length=10000),
        ),
    ]
