# Generated by Django 3.1.13 on 2022-04-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_auto_20220425_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='date',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
