# Generated by Django 3.1.13 on 2022-04-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='staff_owner',
            field=models.CharField(default='anonymous', max_length=1000),
        ),
    ]
