# Generated by Django 3.1.13 on 2022-04-28 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation', '0005_quotation_staff_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='staff_owner',
        ),
        migrations.AddField(
            model_name='quotation',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_owner', to='accounts.account'),
            preserve_default=False,
        ),
    ]
