# Generated by Django 3.1.13 on 2022-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_auto_20220428_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='allocated_quotes',
            field=models.IntegerField(default=0),
        ),
    ]
