# Generated by Django 3.1.13 on 2022-05-09 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation', '0007_quotation_allocated_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotations', models.IntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_owner_quote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
