# Generated by Django 3.1.13 on 2022-05-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_quotation_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='staff',
        ),
        migrations.AddField(
            model_name='quotation',
            name='staff_owner',
            field=models.CharField(default='anonymous', max_length=1000),
        ),
    ]
