# Generated by Django 3.1.13 on 2022-05-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0010_quotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='allocated_quotes',
        ),
    ]
