# Generated by Django 3.1.13 on 2022-05-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_remove_quotation_allocated_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_haulage', models.CharField(blank=True, max_length=1000)),
                ('customs_documentation', models.CharField(blank=True, max_length=1000)),
                ('origin_terminal_handling', models.CharField(blank=True, max_length=1000)),
                ('other_charges', models.CharField(blank=True, max_length=1000)),
                ('freight_cost', models.CharField(blank=True, max_length=1000)),
                ('other_freight_charges', models.CharField(blank=True, max_length=1000)),
                ('total_origin', models.CharField(blank=True, max_length=1000)),
                ('terminal_handling', models.CharField(blank=True, max_length=1000)),
                ('port_charges', models.CharField(blank=True, max_length=1000)),
                ('agency_fee', models.CharField(blank=True, max_length=1000)),
                ('transport_delivery', models.CharField(blank=True, max_length=1000)),
                ('other_destination_charges', models.CharField(blank=True, max_length=1000)),
                ('hs_code', models.CharField(blank=True, max_length=1000)),
                ('fob_value', models.CharField(blank=True, max_length=1000)),
                ('freight_charges', models.CharField(blank=True, max_length=1000)),
                ('insurance', models.CharField(blank=True, max_length=1000)),
                ('customs_value', models.CharField(blank=True, max_length=1000)),
                ('import_duty', models.CharField(blank=True, max_length=1000)),
                ('excise_duty', models.CharField(blank=True, max_length=1000)),
                ('vat', models.CharField(blank=True, max_length=1000)),
                ('railway_levy', models.CharField(blank=True, max_length=1000)),
                ('idf_fee', models.CharField(blank=True, max_length=1000)),
                ('levies', models.CharField(blank=True, max_length=1000)),
                ('total_tax', models.CharField(blank=True, max_length=1000)),
                ('grand_total', models.CharField(blank=True, max_length=1000)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='quotation.quotation')),
            ],
        ),
    ]
