# Generated by Django 3.1.13 on 2022-05-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_staff_quotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='staff',
            new_name='quotation',
        ),
    ]
