# Generated by Django 3.1.13 on 2022-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0013_auto_20220521_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='agency_fee',
            new_name='agent_name',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='customs_documentation',
            new_name='buying_agency_fee',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='freight_cost',
            new_name='buying_customs_documentation',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='origin_haulage',
            new_name='buying_freight_cost',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='origin_terminal_handling',
            new_name='buying_origin_haulage',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='other_charges',
            new_name='buying_origin_terminal_handling',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='other_destination_charges',
            new_name='buying_other_charges',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='other_freight_charges',
            new_name='buying_other_destination_charges',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='port_charges',
            new_name='buying_other_freight_charges',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='terminal_handling',
            new_name='buying_port_charges',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='total_origin',
            new_name='buying_terminal_handling',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='transport_delivery',
            new_name='buying_total_origin',
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='buying_transport_delivery',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_agency_fee',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_documentation',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_freight_cost',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_origin_haulage',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_origin_terminal_handling',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_other_charges',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_other_destination_charges',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_other_freight_charges',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_port_charges',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_terminal_handling',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_total_origin',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_transport_delivery',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_agency_fee',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_documentation',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_freight_cost',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_origin_haulage',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_origin_terminal_handling',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_other_charges',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_other_destination_charges',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_other_freight_charges',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_port_charges',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_terminal_handling',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_total_origin',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_transport_delivery',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
