# Generated by Django 3.1.13 on 2022-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0014_auto_20220521_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_quotation',
            name='buying_port_charges_dest',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_port_charges_dest',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_port_charges_dest',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
