# Generated by Django 3.1.13 on 2022-05-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0016_auto_20220521_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='margin_documentation',
            new_name='margin_customs_documentation',
        ),
        migrations.RenameField(
            model_name='staff_quotation',
            old_name='selling_documentation',
            new_name='selling_customs_documentation',
        ),
    ]
