# Generated by Django 3.1.13 on 2022-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0017_auto_20220522_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_quotation',
            name='buying_total_destination',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='margin_total_destination',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_quotation',
            name='selling_total_destination',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
