# Generated by Django 3.1.13 on 2022-05-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0019_auto_20220522_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_quotation',
            name='agent_name',
            field=models.CharField(max_length=1000),
        ),
    ]
