# Generated by Django 3.1.13 on 2022-05-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0020_auto_20220523_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_quotation',
            name='buying_customs_documentation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
