# Generated by Django 3.1.13 on 2022-05-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0023_auto_20220523_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('supervisor', 'Supervisor'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
