# Generated by Django 3.1.13 on 2022-05-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0024_staff_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff_quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
