# Generated by Django 3.1.13 on 2022-05-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0025_auto_20220523_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_admin', models.CharField(choices=[('approved', 'Approved'), ('ammend', 'Ammend'), ('rejected', 'Rejected')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_admin', to='quotation.quotation')),
            ],
        ),
    ]
