# Generated by Django 3.1.13 on 2022-06-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0026_admin_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('approved_admin', 'Approved_Admin'), ('approved_client', 'Approved_Client'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
