# Generated by Django 3.1.13 on 2022-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0028_auto_20220624_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation_Air',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoterms', models.CharField(blank=True, choices=[('EX', 'EX Works'), ('FOB', 'FOB'), ('CRF', 'CRF'), ('DAP', 'DAP'), ('OTHER', 'Other')], default='EX', max_length=20, null=True)),
                ('other_vas', models.CharField(blank=True, max_length=1000, null=True)),
                ('cargo_weight', models.CharField(blank=True, max_length=200, null=True)),
                ('cargo_length', models.IntegerField()),
                ('cargo_width', models.IntegerField()),
                ('cargo_height', models.IntegerField()),
                ('country_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('cargo_description', models.CharField(max_length=500)),
                ('goods_category', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('special_instructions', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quotation',
            name='cargo_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='cargo_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='cargo_width',
            field=models.IntegerField(),
        ),
    ]
