# Generated by Django 3.2.4 on 2021-07-10 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refno', models.CharField(max_length=10000000000000)),
                ('vessel_arrival', models.CharField(max_length=1000)),
                ('entry_transmitted', models.CharField(max_length=1000)),
                ('import_duty_tax', models.CharField(max_length=10)),
                ('exemption_app', models.CharField(max_length=10)),
                ('coc', models.CharField(max_length=100)),
                ('customs_ver', models.CharField(max_length=100)),
                ('kebs_release', models.CharField(max_length=100)),
                ('customs_release', models.CharField(max_length=100)),
                ('loaded_out', models.CharField(max_length=100)),
                ('delivery_client', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FreightForwarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('refno', models.CharField(max_length=10000000000000)),
                ('etd', models.DateField()),
                ('eta', models.DateField()),
                ('sailingstatus', models.CharField(max_length=1000)),
                ('update', models.CharField(max_length=1000)),
                ('staffcomments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SeaFreightShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=1000)),
                ('refno', models.CharField(max_length=1000)),
                ('billofnumber', models.CharField(max_length=1000)),
                ('incoterms', models.CharField(max_length=1000)),
                ('cargo_description', models.CharField(max_length=2000)),
                ('placeofloading', models.CharField(max_length=2000)),
                ('placeofdelivery', models.CharField(max_length=2000)),
                ('containersize', models.CharField(blank=True, max_length=2000)),
                ('unitsize', models.IntegerField(blank=True)),
                ('unittype', models.CharField(max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user_sea', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoadFreightShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=1000)),
                ('refno', models.CharField(max_length=1000)),
                ('billofnumber', models.CharField(max_length=1000)),
                ('incoterms', models.CharField(max_length=1000)),
                ('cargo_description', models.CharField(max_length=2000)),
                ('placeofloading', models.CharField(max_length=2000)),
                ('placeofdelivery', models.CharField(max_length=2000)),
                ('cargoload', models.CharField(max_length=2000)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user_road', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirFreightShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=1000)),
                ('refno', models.CharField(max_length=1000)),
                ('billofnumber', models.CharField(max_length=1000)),
                ('incoterms', models.CharField(max_length=1000)),
                ('cargo_description', models.CharField(max_length=2000)),
                ('placeofloading', models.CharField(max_length=2000)),
                ('placeofdelivery', models.CharField(max_length=2000)),
                ('weight', models.CharField(max_length=2000)),
                ('packagesno', models.IntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user_air', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
