# Generated by Django 3.2.4 on 2021-07-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airfreightship',
            name='customerref',
            field=models.CharField(default='000', max_length=1000),
        ),
        migrations.AddField(
            model_name='airfreightship',
            name='shippingline',
            field=models.CharField(default='000', max_length=1000),
        ),
        migrations.AddField(
            model_name='roadfreightship',
            name='customerref',
            field=models.CharField(default='000', max_length=1000),
        ),
        migrations.AddField(
            model_name='roadfreightship',
            name='shippingline',
            field=models.CharField(default='000', max_length=1000),
        ),
        migrations.AddField(
            model_name='seafreightship',
            name='customerref',
            field=models.CharField(default='000', max_length=1000),
        ),
        migrations.AddField(
            model_name='seafreightship',
            name='shippingline',
            field=models.CharField(default='000', max_length=1000),
        ),
    ]
