# Generated by Django 3.2.4 on 2021-07-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20210710_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seafreightship',
            name='unitsize',
            field=models.IntegerField(),
        ),
    ]
