# Generated by Django 3.2.4 on 2021-07-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_seafreightship_unitsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='airfreightship',
            name='consignee',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airfreightship',
            name='son',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadfreightship',
            name='consignee',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadfreightship',
            name='son',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seafreightship',
            name='consignee',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seafreightship',
            name='son',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
