# Generated by Django 3.2.4 on 2021-07-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20210713_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadfreightship',
            name='current_eta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadfreightship',
            name='current_etd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
