# Generated by Django 3.2.4 on 2021-07-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20210714_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadfreightship',
            name='current_sailingstatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
