# Generated by Django 3.2.4 on 2023-01-30 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='agencycharges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='clearancecosts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='dateexecuted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='payments',
            name='dutybyus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='freightfees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='invoiceno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payments',
            name='kpademurr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='misc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='originfees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='terminalhandling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='totalcosts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transportcharges',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
