# Generated by Django 3.2.4 on 2021-07-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_roadfreightship_current_sailingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightforwarding',
            name='eta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freightforwarding',
            name='etd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freightforwarding',
            name='staffcomments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='freightforwarding',
            name='update',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
