# Generated by Django 3.2.4 on 2023-01-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_auto_20230130_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='clearancecosts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
