# Generated by Django 3.2.4 on 2021-08-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_auto_20210718_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='airfreightship',
            name='shippingstatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadfreightship',
            name='shippingstatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seafreightship',
            name='shippingstatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
