# Generated by Django 3.2.4 on 2021-08-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_auto_20210827_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightforwarding',
            name='shippingstatus',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
