# Generated by Django 3.2.4 on 2021-08-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_freightforwarding_shippingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airfreightship',
            name='shippingstatus',
            field=models.CharField(blank=True, default='in-progress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seafreightship',
            name='shippingstatus',
            field=models.CharField(blank=True, default='in-progress', max_length=100, null=True),
        ),
    ]
