# Generated by Django 3.2.4 on 2022-02-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_auto_20210828_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadfreightship',
            name='shippingstatus',
            field=models.CharField(blank=True, default='in-progress', max_length=100, null=True),
        ),
    ]
