<<<<<<< HEAD
# Generated by Django 3.2.4 on 2022-02-01 10:17
=======
# Generated by Django 3.2.4 on 2022-01-31 18:01
>>>>>>> f34fcd9ff8f01c5be0fa28925e39db35a9c1fed1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_auto_20210828_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadfreightship',
            name='shippingstatus',
            field=models.CharField(blank=True, default='in-progress', max_length=100, null=True),
        ),
    ]
