# Generated by Django 3.1.13 on 2022-07-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_quote_air'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_Road',
            fields=[
                ('quote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quote.quote')),
                ('truck_type', models.CharField(choices=[('Van', 'Van'), ('3T Truck', '3T Truck'), ('5T Truck', '5T Truck'), ('7T Truck', '7T Truck'), ('15T Truck', '15T Truck'), ('28T Truck', '28T Truck')], max_length=30)),
                ('cargo_weight', models.FloatField()),
                ('cargo_dimension_length', models.FloatField()),
                ('cargo_dimension_width', models.FloatField()),
                ('cargo_dimension_height', models.FloatField()),
            ],
            bases=('quote.quote',),
        ),
        migrations.CreateModel(
            name='Quote_Sea',
            fields=[
                ('quote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quote.quote')),
                ('container_size', models.FloatField(max_length=100)),
                ('container_dimension_length', models.FloatField()),
                ('container_dimension_width', models.FloatField()),
                ('container_dimension_height', models.FloatField()),
            ],
            bases=('quote.quote',),
        ),
    ]
