# Generated by Django 3.1.13 on 2022-07-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20220722_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotetype',
            name='type',
            field=models.CharField(choices=[('Air', 'Air'), ('Sea', 'Sea'), ('Road', 'Road'), ('Warehouse', 'Warehouse')], default='Air', max_length=30),
        ),
    ]
