# Generated by Django 3.1.13 on 2022-07-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_quote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
