# Generated by Django 3.1.13 on 2022-07-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_quote_air_quote_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_air',
            name='quote_owner',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_owner',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
