# Generated by Django 3.1.13 on 2022-07-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0013_auto_20220726_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_road',
            name='quote_owner',
            field=models.CharField(default='000', max_length=30),
        ),
        migrations.AddField(
            model_name='quote_sea',
            name='quote_owner',
            field=models.CharField(default='000', max_length=30),
        ),
    ]
