# Generated by Django 3.1.13 on 2022-07-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0016_auto_20220727_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_serial_no',
        ),
        migrations.AddField(
            model_name='quote',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
