# Generated by Django 3.1.13 on 2022-07-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0017_auto_20220727_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='slug',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_serial_no',
            field=models.CharField(default='000', max_length=30),
        ),
    ]
