# Generated by Django 3.1.13 on 2022-08-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0024_quote_app_quote_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_warehouse',
            name='quote_serial_no',
            field=models.CharField(default='000', max_length=30),
        ),
    ]
