# Generated by Django 3.1.13 on 2022-08-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0026_staff_pricing_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_app',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('approved_admin', 'Approved_Admin'), ('approved_client', 'Approved_Client'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
