# Generated by Django 3.1.13 on 2022-07-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_type',
            name='owner',
        ),
    ]
